### PR TITLE
Breaking Goods

### PR DESCRIPTION
**Pull request by line-o**
Restructured the code a bit to re-use RPC clients and have less options to pass to each method call.
... and then there are tests.

More detailed info can be found in the commit messages :)

### CODE REVIEW

**Comment by olvidalo** [comment]
This is excellent, thank you!

**Comment by line-o** [comment]
Nice to hear. But hold on for a minute, there are some smaller issues that can be merged along with this.

**Comment by olvidalo** [comment]
Sure thing. 

Just some minor suggestions in the meantime:
- I'd rather stick with .dest instead of sendTo. I'm a fan of sticking to conventions if it's not detrimental to usefulness and .dest ist just what gulp plugins use to send files somewhere.
- name the "retry" option a bit more significantly to make it excplicit it's not a normal retry but a retry with a different approach. Maybe retryBinary or could be a compromise? :)

**Comment by line-o** [comment]
Yeah, sure we can discuss names.
What about `retryAsBinary` or `invalidXMLAsBinary` or something? Actually, we should think about something like `HTML5asBinary` if that is the sole purpose.
To me `.dest` sets a destination but does not actually write. But it is really not that important to fight about. Just a personal preference, I guess. Just never been a fan of that method name :)

**Comment by olvidalo** [comment]
I think `invalidXMLAsBinary` or maybe `nonWellformedXMLAsBinary` might be the most appropriate names even if they are a bit clumsy, as they point out that you have be cautious to not accidentally store invalid XML when there are both general XML files and HTML5 files in a project. 

I think the `dest` name make sense insofar as in gulp terminology you set a destination and then pipe something into it. But you're right, it's really not that important ;)

**Comment by JoernT** [comment]
just my 2 cents: 

actually the binary option is there solely for the purpose of storing non-wellformed HTML5. The Java actually checks for the html ending so other XML language are not affected. That much just for clarification.

So - for me 'binaryHTML' or 'HTMLasbinary' would be appropriate names.

**Comment by olvidalo** [comment]
Which exist version are you using @JoernT? I just had a try and for me with 2.2, it would reject an invalid XML file even with an .xml extension.

**Comment by line-o** [comment]
@olvidalo: Maybe @JoernT meant that you cannot upload a malformed XML file as binary even it you change its mime type.

Thanks for the clarification, BTW. Lets call it `htmlAsBinary` then.

**Comment by olvidalo** [comment]
@line-o But you can! It's definitely possible to store malformed XML as binary.

**Comment by line-o** [comment]
Lets test this.

**Comment by line-o** [comment]
Yes, you can. Lets stick to invalidXMLasBinary then.

**Comment by olvidalo** [comment]
Yep. Thanks again for your contributions @line-o. I'll do a little testing with my projects, then merge and put a release out shortly.

**Comment by JoernT** [comment]
regarding the question of eXistdb version you need a 3.0 develop version after 18th Nov 2015. This is when the relevant code changes were merged. Would be good to mention that in the docs.

**Comment by JoernT** [comment]
i would prefer 'htmlasBinary' as this expresses the purpose. It's a non-purpose to store invalid XML (and actually you _can't_ do that as eXistdb will consider only files of mimetype HTML for storage as binary). Furthermore non-wellformed markup is NOT XML per definitionem which makes the name quite misleading. Invalid XML on the other hand has different meanings (invalidness with respect to some kind of schema) but not non-wellformed markup.

This feature was added to eXistdb especially support web components which often use non-wellformed HTML5 syntax (marker attributes). These can be considered resources (not data) to the application and never get indexed, searched or otherwise processed by eXistdb. It's just there to be served to the browser from within a xar application just like a CSS, image, script or other filetype that is not part of the dataset of the app. Sorry for the lenghty excurse but i hope that helps to understand the context better.

The name shouid denote the purpose and not it's abuses. I never ever want to store broken XML - non-wellformed HTML5 on the other hand is no XML.

**Comment by olvidalo** [comment]
The problem I have with `htmlAsBinary` is that at least with eXist 2.2, enabling it will lead to broken XML being stored as binary resources. So storing HTML5 as binary is it's purpose, but what it actually DOES is to force storage of all non-wellformed XML files as binary. 

It was my understanding that this is a workaround for getting HTML5 templates used by frameworks like Polymer stored in eXist. Now I personally don't actually use any HTML5 in my apps so I am not exactly sure how eXist's handling of these files differs between versions.

As said before, at least with eXist 2.2, you can definitely force storage of any non-wellformed XML (and thus HTML5) as a binary resource. A 3.0 devel version is not required for it. Now if I can actually do anything useful with such a resource is another question. Could you maybe expand a little on how eXist changed handling of invalid XML in 3.0 and for what exactly a develop version after 18th Nov 2015 is needed?

**Comment by olvidalo** [comment]
Regardless, I am thinking we should just name it `html5AsBinary`and then have gulp-exist only apply it to files with an `.html` extension. Because for files with other extensions where this option could be useful (say whatever some JS framework would call it's template files) eXist does not expect well-formed XML anyway. Right?

**Comment by line-o** [comment]
Yep, this sounds reasonable. `html5AsBinary` it is now with additional client-side filtering of files by extension.
@JoernT my tests ran on 3.0-LTS and I was also able to upload XML-files as binary.

**Comment by JoernT** [comment]
ok, i wasn't aware that you could do that via the xmlrpc (that's what the plugin is using right?) interface. But you cannot deploy a xar with non-wellformed XML-types. The result (for versions before the aforementioned) always was that the file was not deployed into the database at all. 

So, IMO this can be rather considered a bug in the XMLRPC. Should be more restrictive here as broken XML is really never desired - but that just to get it sorted.

I agree with 'html5asBinary' and filtering - gives us an extra layer to prevent errors for the older versions. Now, regarding the patch: we've added the ability to eXistdb to deploy HTML5 (non-wellformed) from xar applications. This patch only considers files with the html mimetype. If XML parsing fails, it checks wether the mimetype is HTML as stores it as binary anyway in contrast to disregarding that file silently. Furthermore we've done little extensions in XQuery to allow imperative storage of binary content and in eXide to allow to edit such files and store them again as binary. Otherwise the workflow would have seriously been broken.

And just to further outline the purpose: yes, it's purpose is to allow HTML5 doctype and yes, in my case with web components in mind. But there are many more examples and motivations to use HTML5. And as much i am an XML enthusiast i cannot deny some of the advantages. E.g. this

`<div>`

is an valid HTML5 document - the parser will create all the boilerplate for me. The lazy author may fancy this ;)

But to be clear - the use of HTML5 is restricted to pages that can be considered static or opaque from the view of the database. They are application pages or components thereof - not data. They are never processed in any way by eXistdb but just served to the browser as HTML. If you prefer to use client-side templating or require the HTML doctype you can freely do so now and also store your application pages as binary HTML5 and still be able to use xar packaging and eXide. 

btw, thanks guys for the great work on this plugin!

**Comment by olvidalo** [comment]
Thanks for the clarification @JoernT! I think I understand now where the confusion arose from. So if I have HTML5 files in my project, I can't deploy it using a xar file to eXist below 3.0 devel from 18. Nov '15, correct? If so, I should add that hint to the readme. 

BTW, so when only deploying using gulp-exist (I for example use it to deploy to the remote live instance too, I don't use xar files), it might still be possible to use binary HTML5 resources in eXist 2.2 apart from opening them in Exide. That could be useful for some who are stuck with using 2.2 (like me for now, at least until I know when 3.0 final actually comes out).

**Pull request merged**
