### PR TITLE
package update

### PR DESCRIPTION
**Pull request by line-o**
breaking: update dependencies

    - switch to gulp4 (BREAKING)
    - replace deprecated gulp-util with fancy-log and plugin-error
    - update to node-exist 0.3.0
    - update tape, standard, lodash, through2 to latest

fixed: tests
updated: readme
chore: add package-lock.json and add exist and node versions to test matrices (AppVeyor and Travis)

### CODE REVIEW

**Comment by olvidalo** [comment]
Thanks! 🎉 

Looks good. Interestingly it still works for my projects even before updating them to gulp 4. But yeah, still better to mark this as breaking.

**Comment by line-o** [comment]
I should have marked this as WIP to have a chance to rewrite history a bit for cosmetics :)

**Comment by olvidalo** [comment]
It's not THAT ugly ;)

**Comment by olvidalo** [comment]
But next time please do, so I won't jump to conclusions

**Pull request merged**
