### PR TITLE
ci: update to docker based build

### PR DESCRIPTION
**Pull request by line-o**

### CODE REVIEW

**Comment by line-o** [comment]
I accidentally [...] the whole appveyor build.

**Review by duncdrum — COMMENTED** [review]
While i see the value of `win` tests in principle for this repo, i do prefer the low maintenance use of docker to check against upcoming changes.
Travis in combination with the `semantic-release` tool won't do `win` because of a known issue regarding encrypted env variable. I d be happy to merge if you inline a win build into the matrix, with some form of comment about that. Alternatively we would need to create a docker based test on appveyor which, for now, is a pain since we don't do win native docker images.

**Comment by line-o** [comment]
@duncdrum I favour having the releases back up running over tests on windows. Should I remove appveyour.yml?

**Comment by olvidalo** [comment]
I added windows tests the time as there were issues on windows that didn't appear on mac/linux that were a show stopper for some not-so-technically-inclined colleagues of mine.  I'd prefer keeping them in as they are with the non-docker builds and with minimal maintenance (no need to test against new exist versions regularly), just to check for basic win compatibility of the script itself. 
Leaving the decision to you though, if you deem the overhead to be too much for a few possible edge cases, go ahead and remove the win ci.

**Comment by duncdrum** [comment]
A bit of context for the windows problems on travis [win-known-issues](https://travis-ci.community/t/current-known-issues-please-read-this-before-posting-a-new-topic/264/4)

**Comment by line-o** [comment]
What I meant was that I deleted the ci folder and it included a file that seems to be crucial for the appveyour build. `ci/setup.ps1`

**Comment by line-o** [comment]
Appveyor seems to work again. (The logs do look problematic, though)

**Pull request merged**
