### PR TITLE
fix(travis):add 5.0.0 release to matrix

### PR DESCRIPTION
**Pull request by duncdrum**

### CODE REVIEW

**Review by line-o — APPROVED** [review]

**Comment by line-o** [comment]
The build failed with
```
Pull an image or a repository from a registry
The command "docker pull $img" failed and exited with 1 during .
```

**Review by line-o — CHANGES_REQUESTED** [review]
the 4.7.1 image seems to be missing

**Comment by duncdrum** [comment]
This should do the trick

**Review by line-o — APPROVED** [review]

**Pull request merged**
